"""Build the blue/white static website. Python standard library only."""
from pathlib import Path
import json,re,html,sys,shutil
SOURCE=Path(__file__).resolve().parents[1]
PRODUCTION='--production' in sys.argv
ROOT=SOURCE/'.build/production' if PRODUCTION else SOURCE
ROOT.mkdir(parents=True,exist_ok=True)
DATA=SOURCE/'content'
if not (DATA/'grants.html').exists():
 old=(ROOT/'palyazatok/index.html').read_text(encoding='utf-8-sig')
 details=re.search(r'<details class="grant-details">.*?</details>',old,re.S)
 (DATA/'grants.html').write_text(details.group(0) if details else '',encoding='utf-8')
services=[
('betonhazas-transzformator-allomasok-gyartasa','Betonházas transzformátor állomások','Gyártás és helyszíni telepítés ipari és energetikai projektekhez.',['Helyszíni adottságok és kapacitásigény egyeztetése','Transzformátorház és villamos komponensek kialakítása','Telepítés, bekötés és műszaki átadás támogatása'],'A betonházas transzformátor állomások tartós, védett megoldást jelentenek az energiaelosztásban. A kialakításnál a rendelkezésre álló helyet, a környezeti hatásokat és az üzembiztonságot egyaránt figyelembe vesszük.'),
('lemezhazas-transzformator-allomasok-gyartasa','Lemezházas transzformátor állomások','Kompakt állomások, a helyszín adottságaihoz igazítva.',['Kompakt állomáskialakítás','Villamos szerelvények és védelmek beépítése','Helyszíni telepítés és beüzemelési támogatás'],'A lemezházas transzformátor állomások rugalmas kialakítást tesznek lehetővé ipari telephelyeken és energetikai beruházásoknál. A műszaki tartalmat a teljesítményigényhez és a csatlakozó hálózathoz igazítjuk.'),
('nagyfeszultsegu-es-erosaramu-berendezesek-gyartasa-szerelese','Erősáramú berendezések','Elosztók, kapcsolók és megszakítók gyártása, szerelése, karbantartása.',['Elosztóberendezések gyártása és szerelése','Kapcsolók, megszakítók és védelmi rendszerek telepítése','Karbantartás, javítás és korszerűsítés'],'Kis-, közép- és nagyfeszültségű villamos berendezések gyártásával és szerelésével foglalkozunk. Új létesítmények kialakításában és meglévő rendszerek korszerűsítésében is részt veszünk.'),
('nagyfeszultsegu-es-erosaramu-meresek-vizsgalat-diagnosztika','Villamos mérések és diagnosztika','Felülvizsgálatok és kábeldiagnosztika az üzembiztonságért.',['Villámvédelmi és villamos biztonságtechnikai felülvizsgálat','Középfeszültségű kábelek diagnosztikája','Védelmi készülékek és megszakítók ellenőrzése'],'A rendszeres villamos vizsgálatok segítik a hibák felismerését és a berendezések állapotának megismerését. Kis-, közép- és nagyfeszültségű rendszerek mérési és diagnosztikai feladatait is vállaljuk.')]
projects=[('Orosháza','Naperőmű állomások'),('Visonta','2,5 MVA száraztranszformátor telepítése'),('SMP Kecskemét','0,4 kV elosztó telepítése'),('SMP Kecskemét','3200 A toksín szerelése'),('Balatonendréd','Naperőmű állomás telepítése')]
def ph(cls=''):return '<div class="picture-space '+cls+'"><span>Kép helye</span></div>'
def link(path,label,cls='button'):return f'<a class="{cls}" href="{path}">{label}<span aria-hidden="true">↗</span></a>'
def service_cards(pre='./',heading='h3'):
 return ''.join(f'<a class="service-card reveal" href="{pre}{s[0]}/"><span class="number">0{i+1}</span><{heading}>{s[1]}</{heading}><p>{s[2]}</p><span class="card-end">Részletek <span aria-hidden="true">↗</span></span></a>' for i,s in enumerate(services))
# Descriptions use only facts already present in the original reference captions.
project_details=[
 ('oroshaza','Naperőmű állomások Orosházán.',0),
 ('visonta','2,5 MVA teljesítményű száraztranszformátor telepítése Visontán.',2),
 ('smp-eloszto','0,4 kV-os villamos elosztó telepítése az SMP kecskeméti helyszínén.',2),
 ('smp-toksin','3200 A névleges áramú toksín szerelése az SMP kecskeméti helyszínén.',2),
 ('balatonendred','Naperőmű állomás telepítése Balatonendréden.',0)]
def project_cards(count=5,hub=False):
 cards=[]
 for i,(city,title) in enumerate(projects[:count]):
  anchor,description,service=project_details[i]
  tag='h2' if hub else 'h3'
  extra=f'<p>{description}</p>'+link('../'+services[service][0]+'/', 'Kapcsolódó szolgáltatás','text-link') if hub else ''
  cards.append(f'<article class="project reveal" id="{anchor}">{ph()}<div class="project-caption"><span class="eyebrow">{city}</span><{tag}>{title}</{tag}>{extra}</div></article>')
 return ''.join(cards)

def cta(pre='./'):
 return f'<section class="contact-band"><div class="container band-inner"><div><span class="eyebrow">Következő lépés</span><h2>Beszéljünk a projektjéről.</h2><p>Egy rövid egyeztetéssel kezdődik a jó műszaki megoldás.</p></div>{link(pre+"kapcsolat/","Kapcsolatfelvétel","button button-white")}</div></section>'
home=f'''<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">K-L Electro Kft. / 2002 óta</span><h1>Villamos kivitelezés.<br><em>Biztos alapokon.</em></h1><p class="intro">A transzformátor állomásoktól a villamos mérésekig. Szakértelem az ipari és energetikai beruházások minden lépéséhez.</p><div class="actions">{link('./kapcsolat/','Ajánlatot kérek')}{link('./szolgaltatasok/','Szolgáltatásaink','text-link')}</div><div class="hero-note"><span class="note-line"></span><span>Gyártás. Kivitelezés. Üzembiztonság.</span></div></div><div class="hero-visual reveal">{ph('hero-picture')}<div class="experience"><strong>2002</strong><span>óta a villamosiparban</span></div></div></div></section>
<div class="capability-bar"><div class="container"><span>Transzformátor állomások</span><span>Erősáramú berendezések</span><span>Mérések és diagnosztika</span></div></div>
<section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">01 / Szolgáltatások</span><h2>Átgondolt megoldások.<br>Megbízható kivitelezés.</h2></div><p>Kis-, közép- és nagyfeszültségű rendszerekhez, az egyedi feladattól az összetett beruházásig.</p></div><div class="service-grid">{service_cards()}</div></div></section>
<section class="section section-tint"><div class="container about-grid"><div class="reveal">{ph('about-picture')}</div><div class="about-copy reveal"><span class="eyebrow">02 / Rólunk</span><h2>Szakmai tapasztalat.<br><em>Személyes hozzáállás.</em></h2><p class="intro">2002 óta dolgozunk azon, hogy a villamos rendszerek biztos alapot adjanak megrendelőink munkájához.</p><p>A K-L Electro Kft. erősáramú kivitelezéssel, transzformátorállomás-gyártással és villamos felülvizsgálatokkal foglalkozik. Székhelyünk Szerencsen, telephelyünk Szentpéterszegen található.</p>{link('./rolunk/','Ismerjen meg minket','text-link')}</div></div></section>
<section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">03 / Referenciák</span><h2>A munkánk a névjegyünk.</h2></div>{link('./referenciak/','Referenciáink','text-link')}</div><div class="projects-grid">{project_cards(3)}</div></div></section>{cta()}'''
content={
'':('Villamos kivitelezés és transzformátor állomások | K-L Electro','Erősáramú kivitelezés, transzformátor állomások gyártása és villamos mérések. K-L Electro Kft., 2002 óta. Szerencs és Szentpéterszeg.',home),
'szolgaltatasok':('Villamosipari szolgáltatások | K-L Electro','Transzformátorállomás-gyártás, erősáramú szerelés, karbantartás, villamos mérések és PLC-automatikák. Ismerje meg a K-L Electro szolgáltatásait.',f'<section class="section"><div class="container"><div class="service-grid">{service_cards("../", "h2")}</div><div class="split-feature">{ph()}<div><span class="eyebrow">További szakterületeink</span><h2>Az egyedi feladatokra is van válaszunk.</h2><p>PLC-s átkapcsoló és vezérlő automatikák, valamint sújtólég- és robbanásbiztos villamos berendezések szerelése és vizsgálata.</p>{link("../kapcsolat/","Egyeztessünk a feladatról","text-link")}</div></div></div></section>'+cta('../')),
'rolunk':('Rólunk – Villamosipari szakértelem 2002 óta | K-L Electro','Ismerje meg a K-L Electro Kft.-t. Erősáramú kivitelezés és transzformátorállomás-gyártás 2002 óta, szerencsi székhellyel és szentpéterszegi telephellyel.',f'<section class="section"><div class="container about-grid">{ph("about-picture")}<div><span class="eyebrow">K-L Electro Kft.</span><h2>A feladathoz igazodó szakértelem.</h2><p class="intro">Több mint két évtized tapasztalat az erősáramú kivitelezésben.</p><p>A megrendelő igényeit és a helyszíni adottságokat figyelembe véve dolgozunk ipari és energetikai projekteken. Tevékenységeink között az elosztóberendezések és kompakt transzformátor állomások gyártása, a helyszíni szerelés, a karbantartás és a villamos felülvizsgálatok egyaránt szerepelnek.</p><p>Székhely: 3900 Szerencs, Árpád köz 8.<br>Telephely: 4121 Szentpéterszeg, Dobó utca 1.</p></div></div></section>'+cta('../')),
'referenciak':('Villamos kivitelezési referenciák | K-L Electro','K-L Electro projektek: naperőmű állomások Orosházán és Balatonendréden, transzformátor-telepítés Visontán, elosztó- és toksínszerelés Kecskeméten.',f'<section class="section"><div class="container"><div class="projects-grid reference-grid">{project_cards(hub=True)}</div></div></section>'+cta('../')),
'palyazatok':('Pályázatok és fejlesztések | K-L Electro','A K-L Electro támogatott beruházásai: kapacitásbővítés, eszközbeszerzés, vállalatirányítás és technológiai fejlesztések.','<section class="section"><div class="container reading"><h2>Támogatott fejlesztéseink</h2><p>Kapacitásbővítés, eszközbeszerzés, vállalatirányítási rendszer és technológiai innováció.</p>'+ph()+(DATA/'grants.html').read_text(encoding='utf-8')+'</div></section>'),
'kapcsolat':('Kapcsolat és ajánlatkérés | K-L Electro','Kérjen ajánlatot: +36 70 383 15 32, arajanlat@klelectro.hu. K-L Electro Kft., Szerencs és Szentpéterszeg. Elérhető hétfőtől péntekig 07–16 óráig.',f'''<section class="section"><div class="container contact-layout"><div><span class="eyebrow">Keressen minket</span><h2>Miben segíthetünk?</h2><div class="contact-row"><span>Ajánlatkérés</span><a href="mailto:arajanlat@klelectro.hu">arajanlat@klelectro.hu</a></div><div class="contact-row"><span>Litvai Zoltán / ügyvezető</span><a href="tel:+36703831532">+36 (70) 383 15 32</a><a href="mailto:litvaiz@klelectro.hu">litvaiz@klelectro.hu</a></div><div class="contact-row"><span>Projekt-előkészítés</span><a href="tel:+36302130502">+36 (30) 213 05 02</a></div><div class="contact-row"><span>Pénzügy</span><a href="tel:+36703831489">+36 (70) 383 14 89</a><a href="mailto:penzugy@klelectro.hu">penzugy@klelectro.hu</a></div><p>Hétfő–péntek: 07:00–16:00</p></div><aside class="enquiry"><span class="eyebrow">Kezdjük az alapokkal</span><h2>Küldje el a terveit.</h2><p>Az ajánlatkéréshez az alábbi információk segítik a közös munkát:</p><ol><li>A beruházás helyszíne</li><li>A feladat rövid műszaki leírása</li><li>A tervezett ütemezés</li><li>Az Ön neve és telefonszáma</li></ol>{link('mailto:arajanlat@klelectro.hu?subject=Aj%C3%A1nlatk%C3%A9r%C3%A9s','Ajánlatkérés e-mailben')}<p class="small">A gomb a levelezőprogramját nyitja meg.</p></aside></div><div class="container locations"><div><span class="eyebrow">Székhely</span><h3>3900 Szerencs,<br>Árpád köz 8.</h3></div><div><span class="eyebrow">Telephely</span><h3>4121 Szentpéterszeg,<br>Dobó utca 1.</h3></div>{ph()}</div></section>''')}
labels={'szolgaltatasok':'Szolgáltatásaink','rolunk':'Rólunk','referenciak':'Referenciáink','palyazatok':'Pályázatok és fejlesztések','kapcsolat':'Kapcsolat és ajánlatkérés'}
for slug,title,desc,items,body in services:
 labels[slug]=title
 content[slug]=(title+' | K-L Electro',desc+' K-L Electro Kft. – Kérjen személyre szabott ajánlatot.',f'<section class="section"><div class="container service-detail"><article>{ph()}<h2>{title}</h2><p class="intro">{body}</p><h3>Miben segítünk?</h3><ul class="task-list">'+''.join('<li>'+v+'</li>' for v in items)+f'</ul><h3>Az ajánlatkéréshez</h3><p>Küldje el a helyszínt, a berendezés vagy hálózat főbb műszaki adatait és a tervezett ütemezést. Ha rendelkezésre áll, csatolja a műszaki dokumentációt is.</p>{link("../kapcsolat/","Ajánlatot kérek")}</article><aside class="service-nav"><span class="eyebrow">Szakterületeink</span>'+''.join(f'<a href="../{v[0]}/"'+(' aria-current="page"' if v[0]==slug else '')+f'>{v[1]} <span aria-hidden="true">↗</span></a>' for v in services)+'</aside></div></section>')

org={'@type':'Electrician','@id':'https://klelectro.hu/#organization','name':'K-L Electro Kft.','url':'https://klelectro.hu/','logo':'https://klelectro.hu/assets/brand/logo.png','telephone':'+36703831532','email':'arajanlat@klelectro.hu','foundingDate':'2002','address':{'@type':'PostalAddress','streetAddress':'Árpád köz 8.','addressLocality':'Szerencs','postalCode':'3900','addressCountry':'HU'},'location':{'@type':'Place','name':'Telephely','address':{'@type':'PostalAddress','streetAddress':'Dobó utca 1.','addressLocality':'Szentpéterszeg','postalCode':'4121','addressCountry':'HU'}},'openingHoursSpecification':{'@type':'OpeningHoursSpecification','dayOfWeek':['Monday','Tuesday','Wednesday','Thursday','Friday'],'opens':'07:00','closes':'16:00'}}
for slug,(title,desc,body) in content.items():
 if slug==services[2][0]:
  body=body.replace('</aside>','<a href="../referenciak/#smp-eloszto">Kapcsolódó referencia: SMP Kecskemét <span aria-hidden="true">↗</span></a></aside>')
 pre='../' if slug else './';url='https://klelectro.hu/'+(slug+'/' if slug else '')
 nav=''.join(f'<a href="{pre}{path}/"'+(' aria-current="page"' if slug==path or (path=='szolgaltatasok' and slug in [v[0] for v in services]) else '')+f'>{label}</a>' for path,label in [('szolgaltatasok','Szolgáltatások'),('rolunk','Rólunk'),('referenciak','Referenciák')])
 graph=[org,{'@type':'WebSite','@id':'https://klelectro.hu/#website','url':'https://klelectro.hu/','name':'K-L Electro Kft.','inLanguage':'hu'},{'@type':'ContactPage' if slug=='kapcsolat' else 'CollectionPage' if slug=='referenciak' else 'WebPage','@id':url+'#page','url':url,'name':title,'description':desc,'inLanguage':'hu','isPartOf':{'@id':'https://klelectro.hu/#website'}}]
 banner=''
 if slug:
  crumbs=[{'@type':'ListItem','position':1,'name':'Főoldal','item':'https://klelectro.hu/'},{'@type':'ListItem','position':2,'name':labels[slug],'item':url}]
  graph.append({'@type':'BreadcrumbList','@id':url+'#breadcrumb','itemListElement':crumbs});graph[2]['breadcrumb']={'@id':url+'#breadcrumb'}
  if slug in [v[0] for v in services]:graph.append({'@type':'Service','name':labels[slug],'url':url,'provider':{'@id':org['@id']}})
  banner=f'<section class="page-banner"><div class="container"><nav class="breadcrumb" aria-label="Morzsanavigáció"><a href="{pre}">Főoldal</a><span aria-hidden="true">/</span><span aria-current="page">{labels[slug]}</span></nav><h1>{labels[slug]}</h1><p>{desc.split(" K-L Electro")[0]}</p></div></section>'
 document=f'''<!doctype html><html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title}</title><meta name="description" content="{html.escape(desc)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="{url}"><meta name="theme-color" content="#284399"><meta property="og:type" content="website"><meta property="og:locale" content="hu_HU"><meta property="og:site_name" content="K-L Electro Kft."><meta property="og:title" content="{title}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:url" content="{url}"><meta property="og:image" content="https://klelectro.hu/assets/brand/logo.png"><meta property="og:image:alt" content="K-L Electro"><meta name="twitter:card" content="summary"><link rel="icon" href="{pre}assets/brand/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{pre}assets/css/blue.css"><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False)}</script><script defer src="{pre}assets/js/blue.js"></script></head><body><a class="skip-link" href="#content">Ugrás a tartalomhoz</a><div class="topline"><div class="container"><span>Villamosipari megoldások 2002 óta</span><a href="tel:+36703831532">+36 (70) 383 15 32</a></div></div><header class="site-header"><div class="container header-inner"><a class="brand" href="{pre}" aria-label="K-L Electro – Főoldal"><img src="{pre}assets/brand/logo.webp" width="1000" height="120" alt="K-L Electro" fetchpriority="high"></a><button class="nav-toggle" type="button" aria-label="Menü megnyitása" aria-expanded="false" aria-controls="primary-navigation"><span></span><span></span></button><nav id="primary-navigation" aria-label="Fő navigáció">{nav}{link(pre+'kapcsolat/','Kapcsolat','button nav-contact')}</nav></div></header><main id="content">{banner}{body}</main><footer><div class="container footer-grid"><div><a class="brand footer-brand" href="{pre}"><img src="{pre}assets/brand/logo.webp" width="1000" height="120" alt="K-L Electro"></a><p>Villamos kivitelezés.<br>Biztos alapokon, 2002 óta.</p></div><div><h2>Fedezze fel</h2>{nav}<a href="{pre}palyazatok/">Pályázatok</a><a href="{pre}kapcsolat/">Kapcsolat</a></div><div><h2>Elérhetőségeink</h2><a href="tel:+36703831532">+36 (70) 383 15 32</a><a href="tel:+36703831489">+36 (70) 383 14 89</a><a href="mailto:arajanlat@klelectro.hu">arajanlat@klelectro.hu</a><p>H–P: 07:00–16:00</p></div><div><h2>Itt talál minket</h2><address>Székhely: 3900 Szerencs, Árpád köz 8.<br><br>Telephely: 4121 Szentpéterszeg, Dobó utca 1.</address></div></div><div class="container footer-bottom"><span>© 2026 K-L Electro Kft.</span><span>Gyártás · Kivitelezés · Diagnosztika</span></div></footer></body></html>'''
 if not PRODUCTION:document=document.replace('index, follow, max-image-preview:large','noindex, follow, max-image-preview:large')
 path=ROOT/slug/'index.html' if slug else ROOT/'index.html'
 path.parent.mkdir(parents=True,exist_ok=True);path.write_text(document,encoding='utf-8')
# Keep the deployable production directory separate from the GitHub demo.
if PRODUCTION:
 shutil.copytree(SOURCE/'assets',ROOT/'assets',dirs_exist_ok=True)
 shutil.copyfile(DATA/'production.htaccess',ROOT/'.htaccess')
 error=(SOURCE/'404.html').read_text(encoding='utf-8').replace('/klelectrodemo/','/')
 (ROOT/'404.html').write_text(error,encoding='utf-8')
(ROOT/'.nojekyll').write_text('',encoding='utf-8')
robots='User-agent: *\nAllow: /\n'+('\nSitemap: https://klelectro.hu/sitemap.xml\n' if PRODUCTION else '# Demo: pages carry noindex; allow crawlers to read it.\n')
(ROOT/'robots.txt').write_text(robots,encoding='utf-8')
urls=['https://klelectro.hu/'+(slug+'/' if slug else '') for slug in content]
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in urls)+'</urlset>',encoding='utf-8')
print('Built 10 pages: '+('indexable production in .build/production' if PRODUCTION else 'noindex GitHub demo'))
